In [1]:
import pandas as pd

In [2]:
data_df = pd.read_csv('C:\\Users\\nikhi\\Downloads\\RBC Hackathon\\Py\\load_weather_aggregated.csv')
data_df.tail()

,DATE,Year,Month,Day,Time (LST),Temp (°C),Dew Point Temp (°C),Rel Hum (%),Wind Dir (10s deg),Wind Spd (km/h),Wind Spd Flag,Stn Press (kPa),Hmdx,Wind Chill,Load [MW]
10229,2020-12-31 19:00,2020,12,31,19:00,3.3,0.4,81.0,27.0,15.0,NaN,101.49,NaN,NaN,1521.92
10230,2020-12-31 20:00,2020,12,31,20:00,2.9,-0.3,79.0,27.0,16.0,NaN,101.58,NaN,NaN,1463.28
10231,2020-12-31 21:00,2020,12,31,21:00,2.3,-0.6,81.0,27.0,12.0,NaN,101.65,NaN,NaN,1404.85
10232,2020-12-31 22:00,2020,12,31,22:00,2.2,-0.8,81.0,27.0,13.0,NaN,101.70,NaN,NaN,1359.48
10233,2020-12-31 23:00,2020,12,31,23:00,2.2,-1.3,77.0,27.0,14.0,NaN,101.76,NaN,NaN,1369.47

In [3]:
data_df = data_df.drop('DATE', 1)
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10234 entries, 0 to 10233
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 10234 non-null  int64
 1   Month                10234 non-null  int64
 2   Day                  10234 non-null  int64
 3   Time (LST)           10234 non-null  object
 4   Temp (°C)            10219 non-null  float64
 5   Dew Point Temp (°C)  10216 non-null  float64
 6   Rel Hum (%)          10216 non-null  float64
 7   Wind Dir (10s deg)   10097 non-null  float64
 8   Wind Spd (km/h)      10219 non-null  float64
 9   Wind Spd Flag        0 non-null      float64
 10  Stn Press (kPa)      10219 non-null  float64
 11  Hmdx                 1153 non-null   float64
 12  Wind Chill           1331 non-null   float64
 13  Load [MW]            10234 non-null  float64
dtypes: float64(10), int64(3), object(1)
memory usage: 1.1+ MB

In [4]:
data_df['Time (LST)'] = data_df['Time (LST)'].str[:-3]
data_df['Time (LST)'] = pd.to_numeric(data_df['Time (LST)'])
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10234 entries, 0 to 10233
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 10234 non-null  int64
 1   Month                10234 non-null  int64
 2   Day                  10234 non-null  int64
 3   Time (LST)           10234 non-null  int64
 4   Temp (°C)            10219 non-null  float64
 5   Dew Point Temp (°C)  10216 non-null  float64
 6   Rel Hum (%)          10216 non-null  float64
 7   Wind Dir (10s deg)   10097 non-null  float64
 8   Wind Spd (km/h)      10219 non-null  float64
 9   Wind Spd Flag        0 non-null      float64
 10  Stn Press (kPa)      10219 non-null  float64
 11  Hmdx                 1153 non-null   float64
 12  Wind Chill           1331 non-null   float64
 13  Load [MW]            10234 non-null  float64
dtypes: float64(10), int64(4)
memory usage: 1.1 MB

In [ ]:
data_df.to_csv('C:\\Users\\nikhi\\Downloads\\RBC Hackathon\\Py\\load_weather_processed.csv', index=False)